name: Wd-201 L7 Milestone | Cypress Test

on:
  push:
    branches: ["submission-*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Check out the repository with solutions and tests
        uses: actions/checkout@v2
        with:
          repository: "pupilfirst/wd201-nodejs-solutions"
          path: solution
      - name: Hack to run cypress on root
        run: |
          cp solution/l7/package.json package.json
          cp solution/l7/package-lock.json package-lock.json
      - name: Cypress run with env
        uses: cypress-io/github-action@v4
        continue-on-error: true
        with:
          browser: chrome
          project: ./solution/l7
          env: STUDENT_SUBMISSION_URL=${{needs.repo_check.outputs.submissionUrl}}
      - name: Use Node.js to generate report
        run: |
          cd solution/l7 && node generateReportFromResults.js
      - name: Grade the submission based on test results
        uses: pupilfirst/actions/grading@v1
        with:
          report_file_path: "solution/l7/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Report to LMS the outcome of tests.
        uses: pupilfirst/actions/reporting@v1
        with:
          status: "completed"
          report_file_path: "solution/l7/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
