name: WD-201 | L8 Milestone | Test

on:
  push:
    branches: ["submission-*"]

jobs:
  extract_url:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.get-submission-url.outcome}}
      submissionUrl: ${{steps.get-submission-url.outputs.result}}
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission URL
        uses: actions/github-script@v5
        id: get-submission-url
        continue-on-error: true
        with:
          script: |
            const submission = require('./submission.json')
            return submission.checklist[0].result
          result-encoding: string
      - name: Report invalid repository URL in submission
        if: steps.get-submission-url.outcome != 'success'
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: We failed to extract the URL for your live web application from your submission. Please submit again; if this issue persists, please reach out to our team for support.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
  tests:
    needs: extract_url
    if: needs.extract_url.outputs.outcome == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Check out the repository with solutions and tests
        uses: actions/checkout@v2
        with:
          repository: "pupilfirst/wd201-nodejs-solutions"
          path: solution
      - name: Hack to run cypress on root
        run: |
          cp solution/l8/package.json package.json
          cp solution/l8/package-lock.json package-lock.json
      - name: Cypress run with env
        uses: cypress-io/github-action@v4
        continue-on-error: true
        with:
          browser: chrome
          project: ./solution/l8
          env: STUDENT_SUBMISSION_URL=${{needs.extract_url.outputs.submissionUrl}}
      - name: Use Node.js to generate report
        run: |
          cd solution/l8 && node generateReportFromResults.js
      - name: Grade the submission based on test results
        uses: pupilfirst/actions/grading@v1
        with:
          report_file_path: "solution/l8/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Report to LMS the outcome of tests.
        uses: pupilfirst/actions/reporting@v1
        with:
          status: "completed"
          report_file_path: "solution/l8/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
